name: Publish
on:
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
        with:
          deno-version: '2.4'
          cache: true

      - name: Run Deno tests
        run: deno test --allow-read --allow-net --allow-env
  
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Publish package
        run: npx jsr publish